oracle_databases:                                         # Dictionary describing the databases to be deleted
 - home:
   oracle_home: <your_oracle_home>
   oracle_db_name: <your_db_name>                         # Database name
   state: absent
