hostname: 129.40.76.242               # AIX Lpar hostname where the Database is running.
service_name: prod   # Database service name.
listener_port: 1521                   # Database port number.
# oracle_db_home not needed - oracle_sql module uses Thin mode (pure Python, no Oracle client required)

sql_query:
  - query: |
      select thread#, count(*) groups, bytes/1024/1024 size_mb
      from v$log
      group by thread#, bytes
      order by thread#