databases:
 - oracle_db_name: <your_db_name>                 # Name of the database to run Datapatch.
   oracle_db_home: <your_oracle_home>             # Oracle Home location of the above database.
 - oracle_db_name: <your_db_name_2>
   oracle_db_home: <your_oracle_home_2>
