- name: Run initialization tasks
  ansible.builtin.include_role:
    name: ibm.power_aix_oracle.preconfig
    tasks_from: init.yml

- name: Checking if Upgrade Task was already done
  ansible.builtin.stat:
      path: "{{ done_dir }}/configtools.done"
  register: upgradedone

- name: Fail if Upgrade Task was already done
  ansible.builtin.fail:
     msg: Upgrade is already done. Exiting.
  when: upgradedone.stat.exists

- name: Checking if 19c {{ env_type }} is installed
  ansible.builtin.stat:
      path: "{{ done_dir }}/grid.install.done"
  register: installdone

- name: Checking if prechecks script is already run
  ansible.builtin.stat:
   path: "{{ logs_dir }}/prechecks.log"
  register: prech

- name: Checking current HAS Version
  ansible.builtin.shell: "export ORACLE_HOME={{ grid_home_prev }}; {{ grid_home_prev }}/bin/crsctl query has releaseversion |awk '{print $12}' | sed 's/[][]//g'"
  register: hasversion
  changed_when: false

- name: Setting fact - HAS Version
  ansible.builtin.set_fact:
    has_version: "{{ hasversion.stdout }}"

- name: Templating out prechecks.sh script
  template:
    src:  prechecks.sh.j2
    dest: "{{ scripts_dir }}/prechecks.sh"
    mode: '755'
  when: not prech.stat.exists

- name: Executing prechecks.sh script
  ansible.builtin.command: "ksh93 {{ scripts_dir }}/prechecks.sh"
  become: yes
  become_user: "{{ ora_grid_user }}"
  become_method: su
  register: precheck_out
  when: not prech.stat.exists

- name: Prechecks Script Output
  debug: var=precheck_out.stdout_lines
  when: not prech.stat.exists

- name: Creating Oracle Base directory
  ansible.builtin.file:
    path: "{{ ora_base }}"
    owner: "{{ ora_grid_user }}"
    group: "{{ ora_oinstall_group }}"
    state: directory
    mode: '0775'

- name: Templating out Grid Response File
  ansible.builtin.template:
    src: grid_19c_upgrade.rsp.j2
    dest: "{{ files_dir }}/oracle19c_grid_install.rsp"
    owner: "{{ ora_grid_user }}"
    group: "{{ ora_oinstall_group }}"
    mode: '0644'

- name: Include prep_gi_install.yml 
  ansible.builtin.include_role:
    name: ibm.power_aix_oracle.oracle_install_gi
    tasks_from: prep_gi_install.yml

- name: Include grid_install.yml 
  ansible.builtin.include_role:
    name: ibm.power_aix_oracle.oracle_install_gi
    tasks_from: grid_install.yml

- name: Checking if rootupgrade.sh script was already executed
  ansible.builtin.stat:
   path: "{{ done_dir }}/rootupgrade.done"
  register: configdone

- name: Stopping database services before running rootupgrade.sh
  ansible.builtin.shell: "export ORACLE_HOME={{ grid_home_prev }} && {{ grid_home_prev }}/bin/srvctl stop database -d {{ item.source_db_name }}"
  register: stop_dbs
  failed_when: (stop_dbs.rc not in [0,1,2])
  with_items:
      - "{{ databases }}"  
  no_log: true
  when: not configdone.stat.exists 

- name: Templating out grid_upgrade.sh (rootupgrade.sh) script
  template:
    src: grid_upgrade.sh.j2
    dest: "{{ scripts_dir }}/grid_upgrade.sh"
    owner: "{{ ora_grid_user }}"
    group: "{{ ora_oinstall_group }}"
    mode: '0755'    

- name: Executing grid_upgrade.sh script
  ansible.builtin.command: "ksh93 {{ scripts_dir }}/grid_upgrade.sh"
  register: grid_upgrade_out
- ansible.builtin.debug: var=grid_upgrade_out.stdout

- name: Post Grid Upgrade Steps | Copying config_tools.sh
  template:
    src: config_tools.sh.j2
    dest: "{{ scripts_dir }}/config_tools.sh"
    owner: "{{ ora_grid_user }}"
    group: "{{ ora_oinstall_group }}"
    mode: '0755'

- name: Post {{ env_type }} Upgrade Steps| Executing the Config Tools script
  ansible.builtin.command: "ksh93 {{ scripts_dir }}/config_tools.sh"
  register: config_tools_out
  become: yes
  become_user: "{{ ora_grid_user }}"
  become_method: su
- ansible.builtin.debug: var=config_tools_out.stdout

- name: Post {{ env_type }} Upgrade Steps | Checking if Config Tools is successful.
  ansible.builtin.stat:
   path: "{{ done_dir }}/configtools.done"
  register: postupgrd
  tags: poststep

- name: Removing Stale Files
  ansible.builtin.file:
   path: "{{ files_dir }}/oracle19c_grid_install.rsp"
   state: absent

- name: Post {{ env_type }} Upgrade Steps| Status of {{ env_type }} Services
  ansible.builtin.shell: "export ORACLE_HOME={{ grid_ora_home }} && {{ grid_ora_home }}/bin/crsctl stat res ora.cssd"
  register: check_services
  failed_when: check_services.rc not in [0,1,2]
- ansible.builtin.debug: var=check_services.stdout_lines

- name: Post {{ env_type }} Upgrade Steps | Starting the database services
  ansible.builtin.shell: "export ORACLE_HOME={{ grid_home_prev }} && {{ grid_home_prev }}/bin/srvctl start database -d {{ item.source_db_name }}"
  register: start_dbs
  failed_when: (start_dbs.rc !=0)
  with_items:
      - "{{ databases }}"
  when: postupgrd.stat.exists
  no_log: True
  tags: startdbs

- name: Checking the status of the DBs
  ansible.builtin.shell: "export ORACLE_HOME={{ grid_home_prev }} && {{ grid_home_prev }}/bin/srvctl status database -d {{ item.source_db_name }}"
  become: yes
  become_user: "{{ ora_grid_user }}"
  become_method: su
  with_items:
    - "{{ databases }}"
  ignore_errors: True
  register: state_db
  no_log: true

- name: Status of the DBs
  ansible.builtin.debug:
    msg: " Status: {{ item.item.source_db_name }} {{ item.stdout }}"
  loop: "{{ state_db.results }}"
  loop_control:
    label: "{{ item.item.source_db_name }}"
