BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE oracle_sql_oracledb_test (id NUMBER PRIMARY KEY, test_value VARCHAR2(100) NOT NULL)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/
