---
- hosts: dbhost
  gather_facts: false
  remote_user: oracle
  vars_files:
    - vars/vault.yml
  vars:
    real_oracle_home: /u01/19c/database/dbhome_1

  tasks:
    - name: Test oracle_datapatch
      oracle_datapatch:
        oracle_home: "{{ real_oracle_home }}"
        db_name: prod
        sid: <your_sid>
        hostname: <your_database_host>
        port: 1521
        service_name: prod
        user: sys
        password: "{{ default_dbpass }}"
        output: verbose
        fail_on_db_not_exist: true
      environment:
        ORACLE_HOME: "{{ real_oracle_home }}"
        LD_LIBRARY_PATH: "{{ real_oracle_home }}/lib"
        PATH: "{{ real_oracle_home }}/bin:{{ ansible_env.PATH | default('') }}"