---
- hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    - vars/vault.yml
  tasks:
    - name: Test oracle_privs grant
      oracle_privs:
        hostname: <your_database_host>
        port: 1521
        service_name: prod
        user: sys
        password: "{{ default_dbpass }}"
        mode: sysdba
        state: absent
        privs:
          - CREATE SESSION
        roles:
          - TESTUSER1