- hosts: pilotdb
  remote_user: root
  gather_facts: true
  vars_files:
    - vars/upgrade/upgrade_si_vars.yml
    - vars/vault.yml

  roles:
     - role: podba_si_has_upgrade
       tags: si_has_upgrade

  tasks:

    - name: Import oracle_install role
      ansible.builtin.import_role:
        name: ibm.power_aix_oracle.oracle_install_db
        tasks_from: oracle_install.yml
      tags: oracle_install

    - name: Run podba_db_upgrade role
      ansible.builtin.import_role:
        name: podba_db_upgrade
